# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Hello

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: James Baldwin

description: Stylish Jekyll Theme
author:
  name: 
  email: james*at*jamesbaldwin.co.uk
  github: jimmyjamesbaldwin
  twitter: 
  pinterest: 
  linkedin: jamesbaldwinbu
  bio: My name is James Baldwin and I do cloud stuff. I'm too lazy to write content for a website, so until then enjoy this holding page.
  email_md5: 67ebfdfc579c7c7df10fd7d3ab3eedbb

rss_path: 
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
